CREATE DATABASE IF NOT EXISTS neolibro_db;

USE neolibro_db;

CREATE TABLE IF NOT EXISTS obra(
    id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    codigo CHAR(7) NOT NULL UNIQUE,
    titulo VARCHAR(150) NOT NULL,
    preco DECIMAL(10, 2) UNSIGNED NOT NULL,
    tipo_obra VARCHAR(12) NOT NULL
);

CREATE TABLE IF NOT EXISTS hq(
    id INT UNSIGNED PRIMARY KEY NOT NULL,
    industria VARCHAR(60) NOT NULL,
    edicao INT NOT NULL,
    volume INT NOT NULL,
    FOREIGN KEY (id) REFERENCES obra(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS livro(
    id INT UNSIGNED PRIMARY KEY NOT NULL,
    autor VARCHAR(100) NOT NULL,
    editora VARCHAR(80) NOT NULL,
    publicacao INT NOT NULL,
    paginas INT NOT NULL,
    FOREIGN KEY (id) REFERENCES obra(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS manga(
    id INT UNSIGNED PRIMARY KEY NOT NULL,
    autor VARCHAR(100) NOT NULL,
    editora VARCHAR(80) NOT NULL,
    publicacao INT NOT NULL,
    capitulos INT NOT NULL,
    FOREIGN KEY (id) REFERENCES obra(id) ON DELETE CASCADE
);
 